export const provinceToCities: Record<string, string[]> = {
  Alberta: [
    "Calgary",
    "Edmonton",
    "Red Deer",
    "Lethbridge",
    "Medicine Hat",
    "Grande Prairie",
    "Airdrie",
    "Spruce Grove",
    "Okotoks",
    "Fort McMurray",
  ],
  "British Columbia": [
    "Vancouver",
    "Surrey",
    "Burnaby",
    "Richmond",
    "Abbotsford",
    "Coquitlam",
    "Kelowna",
    "Victoria",
    "Langley",
    "Nanaimo",
  ],
  Manitoba: [
    "Winnipeg",
    "Brandon",
    "Steinbach",
    "Thompson",
    "Portage la Prairie",
    "Winkler",
    "Selkirk",
    "Morden",
    "Dauphin",
    "The Pas",
  ],
  "New Brunswick": [
    "Moncton",
    "Saint John",
    "Fredericton",
    "Dieppe",
    "Miramichi",
    "Edmundston",
    "Bathurst",
    "Campbellton",
    "Riverview",
    "Quispamsis",
  ],
  "Newfoundland and Labrador": [
    "St. John's",
    "Mount Pearl",
    "Corner Brook",
    "Conception Bay South",
    "Paradise",
    "Grand Falls-Windsor",
    "Gander",
    "Portugal Cove-St. Philip's",
    "Happy Valley-Goose Bay",
    "Torbay",
  ],
  "Northwest Territories": [
    "Yellowknife",
    "Hay River",
    "Inuvik",
    "Fort Smith",
    "Behchokǫ̀",
    "Fort Simpson",
    "Norman Wells",
    "Tuktoyaktuk",
    "Fort McPherson",
    "Aklavik",
  ],
  "Nova Scotia": [
    "Halifax",
    "Cape Breton",
    "Dartmouth",
    "Truro",
    "New Glasgow",
    "Sydney",
    "Glace Bay",
    "Amherst",
    "Kentville",
    "Bridgewater",
  ],
  Nunavut: [
    "Iqaluit",
    "Rankin Inlet",
    "Arviat",
    "Baker Lake",
    "Cambridge Bay",
    "Pond Inlet",
    "Igloolik",
    "Kugluktuk",
    "Pangnirtung",
    "Cape Dorset",
  ],
  Ontario: [
    "Toronto",
    "Ottawa",
    "Mississauga",
    "Brampton",
    "Hamilton",
    "London",
    "Markham",
    "Vaughan",
    "Kitchener",
    "Windsor",
    "Richmond Hill",
    "Burlington",
    "Sudbury",
    "Oshawa",
    "Barrie",
  ],
  "Prince Edward Island": [
    "Charlottetown",
    "Summerside",
    "Stratford",
    "Cornwall",
    "Montague",
    "Kensington",
    "Souris",
    "Alberton",
    "Tignish",
    "Georgetown",
  ],
  Quebec: [
    "Montreal",
    "Quebec City",
    "Laval",
    "Gatineau",
    "Longueuil",
    "Sherbrooke",
    "Saguenay",
    "Lévis",
    "Trois-Rivières",
    "Terrebonne",
  ],
  Saskatchewan: [
    "Saskatoon",
    "Regina",
    "Prince Albert",
    "Moose Jaw",
    "Swift Current",
    "Yorkton",
    "North Battleford",
    "Estevan",
    "Weyburn",
    "Lloydminster",
  ],
  Yukon: [
    "Whitehorse",
    "Dawson City",
    "Watson Lake",
    "Haines Junction",
    "Carmacks",
    "Mayo",
    "Faro",
    "Ross River",
    "Teslin",
    "Pelly Crossing",
  ],
}


